#!/usr/bin/env python3
"""
kb_report.py — run the deterministic checks (vault_lint + vault_stats) and write
a single dated Markdown report into the vault. This report is the hand-off from
the "Test" stage of the iteration loop to the "Analyze" stage: agents read it,
and its findings become the agenda for the next grilling round.

Usage:
    python scripts/kb_report.py [--vault PATH] [--out DIR] [--print]

Default output: <vault>/meta/kb-report-<YYYY-MM-DD>.md  (created lazily).
Use --print to also echo to stdout, or --out - for stdout only.
"""
import argparse
import datetime as dt
import os
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent


def resolve_vault(arg):
    if arg:
        return pathlib.Path(arg).expanduser()
    if os.environ.get("OBSIDIAN_VAULT_PATH"):
        return pathlib.Path(os.environ["OBSIDIAN_VAULT_PATH"])
    cfg = pathlib.Path.home() / ".obsidian-wiki" / "config"
    if cfg.exists():
        for line in cfg.read_text().splitlines():
            if line.startswith("OBSIDIAN_VAULT_PATH="):
                return pathlib.Path(line.split("=", 1)[1].strip().strip('"'))
    sys.exit("error: no vault path (use --vault, $OBSIDIAN_VAULT_PATH, or ~/.obsidian-wiki/config)")


def run(script, vault):
    r = subprocess.run([sys.executable, str(HERE / script), "--vault", str(vault)],
                       capture_output=True, text=True)
    return r.stdout, r.returncode


def main():
    ap = argparse.ArgumentParser(description="Aggregate KB health report.")
    ap.add_argument("--vault")
    ap.add_argument("--out", default=None, help="Output dir, or '-' for stdout.")
    ap.add_argument("--print", action="store_true", dest="echo")
    args = ap.parse_args()

    vault = resolve_vault(args.vault)
    today = dt.date.today().isoformat()
    lint_out, lint_rc = run("vault_lint.py", vault)
    stats_out, _ = run("vault_stats.py", vault)

    report = (
        f"---\ntitle: KB Health Report {today}\ntags: [meta, kb-report, obsidian-grill]\n"
        f"created: {dt.datetime.utcnow().isoformat()}Z\n---\n\n"
        f"# Knowledge-Base Health Report — {today}\n\n"
        f"Generated by **obsidian-grill** `kb_report.py`. Deterministic checks below;\n"
        f"run the analyzer agents (see `docs/AGENTS.md`) for the semantic pass, then\n"
        f"feed findings + Open Questions into the next `grill-with-obsidian` round.\n\n"
        f"> lint exit status: {'FAIL (issues found)' if lint_rc else 'pass'}\n\n"
        f"## Deterministic lint\n\n```\n{lint_out.strip()}\n```\n\n"
        f"## Metrics\n\n```\n{stats_out.strip()}\n```\n\n"
        f"## Next-round agenda (fill during Analyze)\n\n"
        f"- [ ] Resolve broken links / orphans from lint\n"
        f"- [ ] Triage agent findings (consistency / coverage / freshness / perspective)\n"
        f"- [ ] Promote unresolved **Open Questions** into the next grilling session\n"
    )

    if args.out == "-":
        print(report)
        return
    out_dir = pathlib.Path(args.out) if args.out else vault / "meta"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"kb-report-{today}.md"
    out_file.write_text(report, encoding="utf-8")
    print(f"wrote {out_file}")
    if args.echo:
        print("\n" + report)


if __name__ == "__main__":
    main()
